import Head from 'next/head';
import Main from '../components/main/main.jsx';
import styles from '../styles/Home.module.css';

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/directory/');
  const data = await res.json();

  if (!data) {
    return {
      notFount: true,
    }
  }

  return {
    props: { dataTree: data },
  };
}

export default function Home({ dataTree }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main data={dataTree} />

    </div>
  )
}
