import Head from 'next/head';
import Main from '../components/main/main.jsx';
import styles from '../styles/Home.module.css';

export const getServerSideProps = async (req, res) => {
  const dir = await fetch('http://localhost:3000/api/read_directory');
  const dirData = await dir.json();

  return {
    props: {
      dirData
    }
  };
};

export default function Home({ dirData }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main data={dirData} />

    </div>
  )
}
