import Head from 'next/head';
import { QueryClient, QueryClientProvider, useQuery } from 'react-query';
import { ReactQueryDevtoolsPanel } from 'react-query/devtools'
import Main from '../components/main/main.jsx';
import styles from '../styles/Home.module.css';

/*
export const getServerSideProps = async (req, res) => {
  const dir = await fetch('http://localhost:3000/api/read_directory?path=');
  const dirData = await dir.json();

  return {
    props: {
      dirData
    }
  };
};*/

const queryClient = new QueryClient();

export default function Home() {
  

  return (
    <QueryClientProvider client={queryClient}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <Main />
        
      <ReactQueryDevtoolsPanel />
      </div>
    </QueryClientProvider>

  )
}
